services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: qualti
      POSTGRES_PASSWORD: qualti
      POSTGRES_DB: qualti_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
