services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: qualti
      POSTGRES_PASSWORD: qualti
      POSTGRES_DB: qualti_dev
    volumes:
      - postgres_data_5434:/var/lib/postgresql/data

volumes:
  postgres_data_5434:
